# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_LdIeHkFYRc6kM53ZoOP3vLj0GCQCNGF
"""

import streamlit as st
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np

# Load dataset
from pathlib import Path

df = pd.read_csv(Path(__file__).parent / "canada_per_capita_income.csv")

# Prepare data
X = df[['year']]
y = df['per capita income (US$)']

# Train the model
model = LinearRegression()
model.fit(X, y)

# Streamlit UI
st.set_page_config(page_title="Canada Income Predictor", page_icon="🇨🇦")

st.title("🇨🇦 Canada Per Capita Income Predictor")
st.write("Predict Canada's per capita income using Linear Regression.")

# User input
year = st.number_input(
    "Enter Year",
    min_value=1960,
    max_value=2100,
    value=2020,
    step=1
)

# Prediction
if st.button("Predict"):
    prediction = model.predict(np.array([[year]]))

    st.success(
        f"Predicted Per Capita Income for {year}: ${prediction[0]:,.2f}"
    )
